In [0]:
import pandas as pd
df = pd.read_csv(filepath_or_buffer='https://raw.githubusercontent.com/avinashjairam/Data-Visualization-Class-Groupwork-/master/completeDatasetWalkingLevels.csv', header=None,sep=',')

df.columns=['Date','Avinash_Steps','Juhan_Steps','Daniel_Steps','Viet_Steps','Avg_Steps','Avinash_Distance','Juhan_Distance','Daniel_Distance','Viet_Distance','Avg_Distance','Avg_Temperature','Humidty_Hours_Above_90','Avg_Wind_Speed','Precipitation','Air_Quality_Index_Value','activity_level']
df.dropna(how="all", inplace=True) # drops the empty line at file-end

df.tail()

Date Avinash_Steps  ... Air_Quality_Index_Value   activity_level
361  10/27/2019          4329  ...                      35        Sedentary
362  10/28/2019         10723  ...                      31    Highly Active
363  10/29/2019           101  ...                      31  Somewhat Active
364  10/30/2019          3356  ...                      38       Low Active
365  10/31/2019           189  ...                      44  Somewhat Active

[5 rows x 17 columns]

In [0]:
# split data table into data X and class labels y
df=df.drop(df.index[0])
X = df.iloc[:,11:16].values
y = df.iloc[:,16].values
print(X)

[['63.5' '0' '7.6' '0' '67']
 ['68' '6' '11.5' '0.22' '44']
 ['56.5' '10' '15.7' '0.37' '39']
 ...
 ['56.5' '15' '4.2' '0.07' '31']
 ['60.5' '24' '3.3' '0.06' '38']
 ['65.5' '18' '6.1' '0.54' '44']]


In [0]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)
X = StandardScaler().fit_transform(X)


In [0]:
import numpy as np
mean_vec = np.mean(X_std, axis=0)
cov_mat = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1)
print('Covariance matrix \n%s' %cov_mat)

Covariance matrix 
[[ 1.00274725  0.03633089 -0.68778386  0.01731353  0.3325006 ]
 [ 0.03633089  1.00274725  0.00996932  0.66060732 -0.12832315]
 [-0.68778386  0.00996932  1.00274725  0.09629132 -0.31237245]
 [ 0.01731353  0.66060732  0.09629132  1.00274725 -0.02514619]
 [ 0.3325006  -0.12832315 -0.31237245 -0.02514619  1.00274725]]


In [0]:
cov_mat = np.cov(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[ 0.59832768  0.23586909 -0.2626406   0.52533003  0.49134309]
 [-0.17947251  0.68338879 -0.07654831  0.40035072 -0.5784713 ]
 [-0.61126322 -0.15484036  0.3417629   0.5904182   0.37011647]
 [-0.19077514  0.67247206  0.20442735 -0.45865427  0.50914821]
 [ 0.4469404   0.03393119  0.8755386   0.0692118  -0.16653778]]

Eigenvalues 
[1.93735476 1.65671099 0.7864197  0.28612542 0.3471254 ]


In [0]:
cor_mat1 = np.corrcoef(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat1)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[ 0.59832768  0.23586909 -0.2626406   0.52533003  0.49134309]
 [-0.17947251  0.68338879 -0.07654831  0.40035072 -0.5784713 ]
 [-0.61126322 -0.15484036  0.3417629   0.5904182   0.37011647]
 [-0.19077514  0.67247206  0.20442735 -0.45865427  0.50914821]
 [ 0.4469404   0.03393119  0.8755386   0.0692118  -0.16653778]]

Eigenvalues 
[1.93204694 1.65217205 0.78426513 0.28534151 0.34617437]


In [0]:
cor_mat2 = np.corrcoef(X.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat2)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[ 0.59832768  0.23586909 -0.2626406   0.52533003  0.49134309]
 [-0.17947251  0.68338879 -0.07654831  0.40035072 -0.5784713 ]
 [-0.61126322 -0.15484036  0.3417629   0.5904182   0.37011647]
 [-0.19077514  0.67247206  0.20442735 -0.45865427  0.50914821]
 [ 0.4469404   0.03393119  0.8755386   0.0692118  -0.16653778]]

Eigenvalues 
[1.93204694 1.65217205 0.78426513 0.28534151 0.34617437]


In [0]:
u,s,v = np.linalg.svd(X_std.T)
u

array([[-0.59832768,  0.23586909, -0.2626406 ,  0.49134309,  0.52533003],
       [ 0.17947251,  0.68338879, -0.07654831, -0.5784713 ,  0.40035072],
       [ 0.61126322, -0.15484036,  0.3417629 ,  0.37011647,  0.5904182 ],
       [ 0.19077514,  0.67247206,  0.20442735,  0.50914821, -0.45865427],
       [-0.4469404 ,  0.03393119,  0.8755386 , -0.16653778,  0.0692118 ]])

In [0]:
for ev in eig_vecs:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))
print('Everything ok!')

Everything ok!


In [0]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort()
eig_pairs.reverse()

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

Eigenvalues in descending order:
1.9320469407690584
1.6521720531702189
0.7842651267844301
0.34617436748789454
0.2853415117883984


In [0]:
tot = sum(eig_vals)
var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

trace1 = dict(
    type='bar',
    x=['PC %s' %i for i in range(1,6)],
    y=var_exp,
    name='Individual'
)

trace2 = dict(
    type='scatter',
    x=['PC %s' %i for i in range(1,6)], 
    y=cum_var_exp,
    name='Cumulative'
)

data = [trace1, trace2]

layout=dict(
    title='Explained variance by different principal components',
    yaxis=dict(
        title='Explained variance in percent'
    ),
    annotations=list([
        dict(
            x=1.16,
            y=1.05,
            xref='paper',
            yref='paper',
            text='Explained Variance',
            showarrow=False,
        )
    ])
)

fig = dict(data=data, layout=layout)
py.iplot(fig, filename='selecting-principal-components')